-- RitualistLocalization.lua
-- ROADMAP v2.1.0 Compliant Localization
-- Supported: enUS, ukUA, deDE, frFR, esES, zhCN. NO ruRU.

local L = {
	enUS = {
		-- Tabs
		MAIN_TAB = "Summon",
		HISTORY_TAB = "History",
		-- Buttons
		BROADCAST_BTN = "Bcast",
		AUTO_SUMMON_BTN = "Next",
		TEST_BTN = "T",
		CLOSE_BTN = "Close",
		-- Headers
		TARGET_COL = "Target",
		EXECUTOR_COL = "Warlock",
		-- Options Labels
		OPT_TITLE = "Ritualist Options",
		OPT_WHISPER = "Whisper on Summon",
		OPT_ZONE = "Include Zone Name",
		OPT_RITUAL = "Soulwell Announce",
		OPT_RANGE = "Range Check",
		OPT_DEBUG = "Debug Mode",
		OPT_ANCHOR = "Show Anchor",
		OPT_MON_HEADER = "Monitor Channels:",
		OPT_LANG = "Language:",
		OPT_SW_HEADER = "Soulwell Announcement:",
		-- EditBox Labels
		EB_SUMMON = "Summon Message ({targetname}):",
		EB_WHISPER = "Whisper Message ({zone}):",
		EB_BROADCAST = "Broadcast Msg (used by button):",
		EB_SOULWELL = "Soulwell Message ({HP}):",
		-- Tooltips
		TT_SETTINGS = "Open Options",
		TT_CLOSE = "Close Window",
		TT_TAB_MAIN = "View active summon queue",
		TT_TAB_HISTORY = "View summon history log",
		TT_HEAD_TARGET = "Sort by Name",
		TT_HEAD_STATUS = "Sort by Status/Distance",
		TT_HEAD_EXECUTOR = "Sort by Warlock",
		TT_BROADCAST = "Announce summon instructions to raid/party",
		TT_AUTO = "Auto-target and summon the next available player",
		TT_TEST = "Populate list with test data (Debug Mode)",
		TT_WHISPER = "Whisper target when starting summon",
		TT_ZONE = "Include zone name in whisper",
		TT_RITUAL = "Announce Soulwell placement",
		TT_RANGE = "Auto-remove players who arrived",
		TT_DEBUG = "Enable debug logging and Test button",
		TT_ANCHOR = "Show/Hide the draggable anchor icon",
		TT_MON_SAY = "Monitor Say chat for '123'",
		TT_MON_PARTY = "Monitor Party chat for '123'",
		TT_MON_RAID = "Monitor Raid chat for '123'",
		TT_MON_GUILD = "Monitor Guild chat for '123'",
		TT_MON_YELL = "Monitor Yell chat for '123'",
		TT_MON_WHISPER = "Monitor Whispers for '123'",
		TT_SW_SAY = "Announce Soulwell in Say",
		TT_SW_PARTY = "Announce Soulwell in Party",
		TT_SW_RAID = "Announce Soulwell in Raid",
		TT_SW_GUILD = "Announce Soulwell in Guild",
		TT_SW_YELL = "Announce Soulwell in Yell",
		TT_EB_SUMMON = "Message sent to chat when you cast Summon",
		TT_EB_WHISPER = "Message whispered to player when you summon them",
		TT_EB_BROADCAST = "Message sent when clicking 'Broadcast'",
		TT_EB_SOULWELL = "Message sent when creating a Soulwell",
		-- Statuses
		TT_STATUS_WAITING = "Waiting for summon",
		TT_STATUS_NEARBY = "Player is nearby",
		TT_STATUS_SUMMONING = "Summoning in progress",
		TT_STATUS_TARGETED = "Warlock is targeting",
		TT_STATUS_ARRIVED = "Player has arrived",
		TT_STATUS_TIMEOUT = "Summon request timed out",
		TT_STATUS_OFFLINE = "Player is offline",
		TT_STATUS_DEAD = "Player is dead",
		TT_STATUS_COMBAT = "Player is in combat",
		TT_STATUS_DONE = "Summon completed",
		TT_STATUS_INTERRUPTED = "Cast interrupted!",
		TT_STATUS_WRONG_ZONE = "Wrong instance/zone",
		ERR_SHARED_PROTECTION = "Manual removal blocked: shared list protection active.",
	},
	ukUA = {
		MAIN_TAB = "Призов",
		HISTORY_TAB = "Історія",
		BROADCAST_BTN = "Анонс",
		AUTO_SUMMON_BTN = "Наст.",
		TEST_BTN = "Т",
		CLOSE_BTN = "Закрити",
		TARGET_COL = "Ціль",
		EXECUTOR_COL = "Лок",
		OPT_TITLE = "Налаштування Ritualist",
		OPT_WHISPER = "Шепіт при призові",
		OPT_ZONE = "Додавати назву зони",
		OPT_RITUAL = "Анонс Криниці",
		OPT_RANGE = "Перевірка дистанції",
		OPT_DEBUG = "Режим налагодження",
		OPT_ANCHOR = "Показувати якір",
		OPT_MON_HEADER = "Слідкувати за чатом:",
		OPT_LANG = "Мова:",
		OPT_SW_HEADER = "Анонс Криниці Душ:",
		EB_SUMMON = "Повідомлення при призові ({targetname}):",
		EB_WHISPER = "Повідомлення у приват ({zone}):",
		EB_BROADCAST = "Текст кнопки Анонс:",
		EB_SOULWELL = "Повідомлення про Криницю ({HP}):",
		TT_SETTINGS = "Відкрити налаштування",
		TT_CLOSE = "Закрити вікно",
		TT_TAB_MAIN = "Черга призову",
		TT_TAB_HISTORY = "Історія призовів",
		TT_HEAD_TARGET = "Сортувати за ім'ям",
		TT_HEAD_STATUS = "Сортувати за статусом",
		TT_HEAD_EXECUTOR = "Сортувати за варлоком",
		TT_BROADCAST = "Відправити інструкцію в чат",
		TT_AUTO = "Авто-вибір наступної цілі",
		TT_TEST = "Заповнити тестовими даними",
		TT_WHISPER = "Шепотіти цілі при початку призову",
		TT_ZONE = "Додавати назву зони до повідомлення",
		TT_RITUAL = "Анонсувати встановлення Криниці Душ",
		TT_RANGE = "Авто-видалення тих, хто вже прибув",
		TT_DEBUG = "Увімкнути налагодження та кнопку Тест",
		TT_ANCHOR = "Показати/приховати якір",
		TT_MON_SAY = "Слідкувати за '123' у Сказати",
		TT_MON_PARTY = "Слідкувати за '123' у Групі",
		TT_MON_RAID = "Слідкувати за '123' у Рейді",
		TT_MON_GUILD = "Слідкувати за '123' у Гільдії",
		TT_MON_YELL = "Слідкувати за '123' у Крику",
		TT_MON_WHISPER = "Слідкувати за '123' у Шепоті",
		TT_SW_SAY = "Анонс Криниці (Сказати)",
		TT_SW_PARTY = "Анонс Криниці (Група)",
		TT_SW_RAID = "Анонс Криниці (Рейд)",
		TT_SW_GUILD = "Анонс Криниці (Гільдія)",
		TT_SW_YELL = "Анонс Криниці (Крик)",
		TT_EB_SUMMON = "Повідомлення у чат при призові",
		TT_EB_WHISPER = "Повідомлення у приват гравцю",
		TT_EB_BROADCAST = "Текст кнопки Анонс",
		TT_EB_SOULWELL = "Повідомлення про Криницю Душ",
		TT_STATUS_WAITING = "Очікує призову",
		TT_STATUS_NEARBY = "Гравець поруч",
		TT_STATUS_SUMMONING = "Йде призов",
		TT_STATUS_ARRIVED = "Гравець прибув",
		TT_STATUS_TIMEOUT = "Час очікування вичерпано",
		TT_STATUS_OFFLINE = "Гравець офлайн",
		TT_STATUS_DEAD = "Гравець мертвий",
		TT_STATUS_COMBAT = "Гравець у бою",
		TT_STATUS_DONE = "Призов завершено",
		TT_STATUS_INTERRUPTED = "Призов перервано!",
		TT_STATUS_WRONG_ZONE = "Неправильна зона/інстанс",
		ERR_SHARED_PROTECTION = "Ручне видалення заблоковано: активна координація.",
	},
	deDE = {
		MAIN_TAB = "Beschwörung",
		HISTORY_TAB = "Verlauf",
		BROADCAST_BTN = "Ansage",
		AUTO_SUMMON_BTN = "Weiter",
		TEST_BTN = "T",
		CLOSE_BTN = "Schließen",
		TARGET_COL = "Ziel",
		EXECUTOR_COL = "Hexer",
		OPT_TITLE = "Ritualist Optionen",
		OPT_WHISPER = "Flüstern beim Beschwören",
		OPT_ZONE = "Zonenname einschließen",
		OPT_RITUAL = "Seelenbrunnen Ansage",
		OPT_RANGE = "Entfernungsprüfung",
		OPT_DEBUG = "Debug-Modus",
		OPT_ANCHOR = "Anker anzeigen",
		OPT_MON_HEADER = "Chat Überwachen:",
		OPT_LANG = "Sprache:",
		OPT_SW_HEADER = "Seelenbrunnen Ansage:",
		EB_SUMMON = "Beschwörungsnachricht ({targetname}):",
		EB_WHISPER = "Flüsternachricht ({zone}):",
		EB_BROADCAST = "Ansagetext:",
		EB_SOULWELL = "Seelenbrunnennachricht ({HP}):",
		TT_SETTINGS = "Optionen öffnen",
		TT_CLOSE = "Fenster schließen",
		TT_TAB_MAIN = "Aktive Beschwörungswarteschlange",
		TT_TAB_HISTORY = "Beschwörungsverlauf",
		TT_HEAD_TARGET = "Nach Name sortieren",
		TT_HEAD_STATUS = "Nach Status sortieren",
		TT_HEAD_EXECUTOR = "Nach Hexer sortieren",
		TT_BROADCAST = "Beschwörungsanweisungen im Chat ansagen",
		TT_AUTO = "Nächstes verfügbares Ziel automatisch beschwören",
		TT_TEST = "Liste mit Testdaten füllen",
		TT_WHISPER = "Ziel beim Start der Beschwörung anflüstern",
		TT_ZONE = "Zonennamen in das Flüstern einbeziehen",
		TT_RITUAL = "Aufstellen des Seelenbrunnens ansagen",
		TT_RANGE = "Spieler, die angekommen sind, automatisch entfernen",
		TT_DEBUG = "Debug-Log und Test-Button aktivieren",
		TT_ANCHOR = "Verschiebbares Anker-Icon anzeigen/ausblenden",
		TT_MON_SAY = "Sagen-Chat auf '123' überwachen",
		TT_MON_PARTY = "Gruppen-Chat auf '123' überwachen",
		TT_MON_RAID = "Schlachtzugs-Chat auf '123' überwachen",
		TT_MON_GUILD = "Gilden-Chat auf '123' überwachen",
		TT_MON_YELL = "Schreien-Chat auf '123' überwachen",
		TT_MON_WHISPER = "Flüstern auf '123' überwachen",
		TT_SW_SAY = "Seelenbrunnen in Sagen ansagen",
		TT_SW_PARTY = "Seelenbrunnen in Gruppe ansagen",
		TT_SW_RAID = "Seelenbrunnen in Schlachtzug ansagen",
		TT_SW_GUILD = "Seelenbrunnen in Gilde ansagen",
		TT_SW_YELL = "Seelenbrunnen in Schreien ansagen",
		TT_EB_SUMMON = "Nachricht bei Beschwörung",
		TT_EB_WHISPER = "Privatnachricht an Spieler",
		TT_EB_BROADCAST = "Text für Ansage-Button",
		TT_EB_SOULWELL = "Nachricht für Seelenbrunnen",
		TT_STATUS_WAITING = "Wartet auf Beschwörung",
		TT_STATUS_NEARBY = "Spieler ist in der Nähe",
		TT_STATUS_SUMMONING = "Beschwörung läuft",
		TT_STATUS_ARRIVED = "Spieler ist angekommen",
		TT_STATUS_TIMEOUT = "Zeitüberschreitung",
		TT_STATUS_OFFLINE = "Spieler ist offline",
		TT_STATUS_DEAD = "Spieler ist tot",
		TT_STATUS_COMBAT = "Spieler ist im Kampf",
		TT_STATUS_DONE = "Beschwörung abgeschlossen",
		TT_STATUS_INTERRUPTED = "Beschwörung unterbrochen!",
		TT_STATUS_WRONG_ZONE = "Falsche Zone/Instanz",
		ERR_SHARED_PROTECTION = "Manuelles Entfernen blockiert: Geteilte Liste geschützt.",
	},
	frFR = {
		MAIN_TAB = "Invocation",
		HISTORY_TAB = "Historique",
		BROADCAST_BTN = "Annonce",
		AUTO_SUMMON_BTN = "Suivant",
		TEST_BTN = "T",
		CLOSE_BTN = "Fermer",
		TARGET_COL = "Cible",
		EXECUTOR_COL = "Démo",
		OPT_TITLE = "Options de Ritualist",
		OPT_WHISPER = "Chuchoter à l'invocation",
		OPT_ZONE = "Inclure le nom de zone",
		OPT_RITUAL = "Annonce Puits d'âmes",
		OPT_RANGE = "Vérif. de distance",
		OPT_DEBUG = "Mode Debug",
		OPT_ANCHOR = "Afficher l'ancre",
		OPT_MON_HEADER = "Surveiller les canaux:",
		OPT_LANG = "Langue:",
		OPT_SW_HEADER = "Annonce du Puits d'âmes:",
		EB_SUMMON = "Message d'invocation ({targetname}):",
		EB_WHISPER = "Message privé ({zone}):",
		EB_BROADCAST = "Message d'annonce:",
		EB_SOULWELL = "Message du Puits ({HP}):",
		TT_SETTINGS = "Ouvrir les options",
		TT_CLOSE = "Fermer la fenêtre",
		TT_TAB_MAIN = "File d'attente active",
		TT_TAB_HISTORY = "Historique des invocations",
		TT_HEAD_TARGET = "Trier par nom",
		TT_HEAD_STATUS = "Trier par statut",
		TT_HEAD_EXECUTOR = "Trier par démoniste",
		TT_BROADCAST = "Annoncer les instructions au groupe",
		TT_AUTO = "Cibler et invoquer automatiquement le suivant",
		TT_TEST = "Remplir avec des données de test",
		TT_WHISPER = "Chuchoter à la cible au début",
		TT_ZONE = "Inclure la zone dans le chuchotement",
		TT_RITUAL = "Annoncer la pose du Puits d'âmes",
		TT_RANGE = "Retirer auto les joueurs arrivés",
		TT_DEBUG = "Activer les logs et le bouton Test",
		TT_ANCHOR = "Afficher/masquer l'icône d'ancrage",
		TT_MON_SAY = "Surвеiller Dire pour '123'",
		TT_MON_PARTY = "Surвеiller Groupe pour '123'",
		TT_MON_RAID = "Surвеiller Raid for '123'",
		TT_MON_GUILD = "Surвеiller Guilde for '123'",
		TT_MON_YELL = "Surвеiller Crier for '123'",
		TT_MON_WHISPER = "Surвеiller Chuchoter for '123'",
		TT_SW_SAY = "Annoncer Puits dans Dire",
		TT_SW_PARTY = "Annoncer Puits dans Groupe",
		TT_SW_RAID = "Annoncer Puits dans Raid",
		TT_SW_GUILD = "Annoncer Puits dans Guilde",
		TT_SW_YELL = "Annoncer Puits dans Crier",
		TT_EB_SUMMON = "Message lors de l'invocation",
		TT_EB_WHISPER = "Message privé au joueur",
		TT_EB_BROADCAST = "Texte du bouton Annonce",
		TT_EB_SOULWELL = "Message pour le Puits",
		TT_STATUS_WAITING = "En attente",
		TT_STATUS_NEARBY = "Joueur proche",
		TT_STATUS_SUMMONING = "Invocation en cours",
		TT_STATUS_ARRIVED = "Joueur arrivé",
		TT_STATUS_TIMEOUT = "Délai expiré",
		TT_STATUS_OFFLINE = "Joueur déconnecté",
		TT_STATUS_DEAD = "Joueur mort",
		TT_STATUS_COMBAT = "Joueur en combat",
		TT_STATUS_DONE = "Invocation terminée",
		TT_STATUS_INTERRUPTED = "Invocation interrompue !",
		TT_STATUS_WRONG_ZONE = "Mauvaise zone/instance",
		ERR_SHARED_PROTECTION = "Suppression manuelle bloquée : protection de liste partagée active.",
	},
	esES = {
		MAIN_TAB = "Invocación",
		HISTORY_TAB = "Historial",
		BROADCAST_BTN = "Anuncio",
		AUTO_SUMMON_BTN = "Sig.",
		TEST_BTN = "T",
		CLOSE_BTN = "Cerrar",
		TARGET_COL = "Objetivo",
		EXECUTOR_COL = "Brujo",
		OPT_TITLE = "Opciones de Ritualist",
		OPT_WHISPER = "Susurrar al invocar",
		OPT_ZONE = "Incluir nombre de zona",
		OPT_RITUAL = "Anuncio de Pozo",
		OPT_RANGE = "Control de rango",
		OPT_DEBUG = "Modo Debug",
		OPT_ANCHOR = "Mostrar ancla",
		OPT_MON_HEADER = "Monitorear canales:",
		OPT_LANG = "Idioma:",
		OPT_SW_HEADER = "Anuncio de Pozo de Almas:",
		EB_SUMMON = "Mensaje de invocación ({targetname}):",
		EB_WHISPER = "Mensaje de susurro ({zone}):",
		EB_BROADCAST = "Mensaje de anuncio:",
		EB_SOULWELL = "Mensaje del Pozo ({HP}):",
		TT_SETTINGS = "Abrir opciones",
		TT_CLOSE = "Cerrar ventana",
		TT_TAB_MAIN = "Ver cola activa",
		TT_TAB_HISTORY = "Ver historial",
		TT_HEAD_TARGET = "Ordenar por nombre",
		TT_HEAD_STATUS = "Ordenar por estado",
		TT_HEAD_EXECUTOR = "Ordenar por brujo",
		TT_BROADCAST = "Anunciar instrucciones al grupo",
		TT_AUTO = "Invocar automáticamente al siguiente",
		TT_TEST = "Llenar con datos de prueba",
		TT_WHISPER = "Susurrar al objetivo al iniciar",
		TT_ZONE = "Incluir zona en el susurro",
		TT_RITUAL = "Anunciar colocación del Pozo",
		TT_RANGE = "Eliminar auto a los que llegaron",
		TT_DEBUG = "Activar logs y botón de prueba",
		TT_ANCHOR = "Mostrar/ocultar icono de ancla",
		TT_MON_SAY = "Monitorear Decir para '123'",
		TT_MON_PARTY = "Monitorear Grupo para '123'",
		TT_MON_RAID = "Monitorear Banda para '123'",
		TT_MON_GUILD = "Monitorear Hermandad para '123'",
		TT_MON_YELL = "Monitorear Gritar para '123'",
		TT_MON_WHISPER = "Monitorear Susurros para '123'",
		TT_SW_SAY = "Anunciar Pozo en Decir",
		TT_SW_PARTY = "Anunciar Pozo en Grupo",
		TT_SW_RAID = "Anunciar Pozo en Banda",
		TT_SW_GUILD = "Anunciar Pozo en Hermandad",
		TT_SW_YELL = "Anunciar Pozo en Gritar",
		TT_EB_SUMMON = "Mensaje al invocar",
		TT_EB_WHISPER = "Mensaje privado al jugador",
		TT_EB_BROADCAST = "Texto del botón Anuncio",
		TT_EB_SOULWELL = "Mensaje para el Pozo",
		TT_STATUS_WAITING = "Esperando",
		TT_STATUS_NEARBY = "Jugador cerca",
		TT_STATUS_SUMMONING = "Invocando...",
		TT_STATUS_ARRIVED = "Jugador llegó",
		TT_STATUS_TIMEOUT = "Tiempo agotado",
		TT_STATUS_OFFLINE = "Desconectado",
		TT_STATUS_DEAD = "Muerto",
		TT_STATUS_COMBAT = "En combate",
		TT_STATUS_DONE = "Invocación completa",
		TT_STATUS_INTERRUPTED = "¡Invocación interrompida!",
		TT_STATUS_WRONG_ZONE = "Zona/Instancia incorrecta",
		ERR_SHARED_PROTECTION = "Eliminación manual bloqueada: protección de lista compartida activa.",
	},
	zhCN = {
		MAIN_TAB = "召唤",
		HISTORY_TAB = "历史",
		BROADCAST_BTN = "广播",
		AUTO_SUMMON_BTN = "下个",
		TEST_BTN = "T",
		CLOSE_BTN = "关闭",
		TARGET_COL = "目标",
		EXECUTOR_COL = "术士",
		OPT_TITLE = "Ritualist 设置",
		OPT_WHISPER = "召唤时密语",
		OPT_ZONE = "包含区域名称",
		OPT_RITUAL = "灵魂之井通报",
		OPT_RANGE = "距离检查",
		OPT_DEBUG = "调试模式",
		OPT_ANCHOR = "显示锚点",
		OPT_MON_HEADER = "监控频道:",
		OPT_LANG = "语言:",
		OPT_SW_HEADER = "灵魂之井通报:",
		EB_SUMMON = "召唤消息 ({targetname}):",
		EB_WHISPER = "密语消息 ({zone}):",
		EB_BROADCAST = "广播消息:",
		EB_SOULWELL = "灵魂之井消息 ({HP}):",
		TT_SETTINGS = "打开设置",
		TT_CLOSE = "关闭窗口",
		TT_TAB_MAIN = "查看当前召唤队列",
		TT_TAB_HISTORY = "查看召唤历史",
		TT_HEAD_TARGET = "按名字排序",
		TT_HEAD_STATUS = "按状态排序",
		TT_HEAD_EXECUTOR = "按术士排序",
		TT_BROADCAST = "向团队广播召唤指令",
		TT_AUTO = "自动选择并召唤下一个玩家",
		TT_TEST = "填充测试数据",
		TT_WHISPER = "开始召唤时密语目标",
		TT_ZONE = "密语中包含区域名",
		TT_RITUAL = "通报灵魂之井投放",
		TT_RANGE = "自动移除已到达的玩家",
		TT_DEBUG = "启用调试日志和测试按钮",
		TT_ANCHOR = "显示/隐藏锚点图标",
		TT_MON_SAY = "监控 说 频道中的 '123'",
		TT_MON_PARTY = "监控 小队 频道中的 '123'",
		TT_MON_RAID = "监控 团队 频道中的 '123'",
		TT_MON_GUILD = "监控 公会 频道中的 '123'",
		TT_MON_YELL = "监控 大喊 频道中的 '123'",
		TT_MON_WHISPER = "监控 密语 中的 '123'",
		TT_SW_SAY = "在 说 频道通报灵魂之井",
		TT_SW_PARTY = "在 小队 频道通报灵魂之井",
		TT_SW_RAID = "在 团队 频道通报灵魂之井",
		TT_SW_GUILD = "在 公会 频道通报灵魂之井",
		TT_SW_YELL = "在大喊 频道通报灵魂之井",
		TT_EB_SUMMON = "召唤时的消息",
		TT_EB_WHISPER = "给玩家的密语消息",
		TT_EB_BROADCAST = "广播按钮文本",
		TT_EB_SOULWELL = "灵魂之井的消息",
		TT_STATUS_WAITING = "等待召唤",
		TT_STATUS_NEARBY = "玩家在附近",
		TT_STATUS_SUMMONING = "正在召唤",
		TT_STATUS_ARRIVED = "玩家已到达",
		TT_STATUS_TIMEOUT = "召唤超时",
		TT_STATUS_OFFLINE = "玩家离线",
		TT_STATUS_DEAD = "玩家死亡",
		TT_STATUS_COMBAT = "玩家在战斗中",
		TT_STATUS_DONE = "召唤完成",
		TT_STATUS_INTERRUPTED = "召唤被中断！",
		TT_STATUS_WRONG_ZONE = "错误的区域/副本",
		ERR_SHARED_PROTECTION = "手动移除被阻止：共享列表保护已启用。",
	},
}

-- Fallback logic
for lang, table in pairs(L) do
	if lang ~= "enUS" then
		for k, v in pairs(L.enUS) do
			if not table[k] then
				table[k] = v
			end
		end
	end
end

function Ritualist_GetL(key)
	local lang = "enUS"
	if RitualistDB and RitualistDB.language then
		lang = RitualistDB.language
	else
		local locale = GetLocale()
		if locale == "ukUA" then
			lang = "ukUA"
		elseif locale == "deDE" then
			lang = "deDE"
		elseif locale == "frFR" then
			lang = "frFR"
		elseif locale == "esES" then
			lang = "esES"
		elseif locale == "zhCN" then
			lang = "zhCN"
		end
	end

	if L[lang] and L[lang][key] then
		return L[lang][key]
	end
	if L["enUS"][key] then
		return L["enUS"][key]
	end
	return key
end
